// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tcc.Context;

#nullable disable

namespace tcc.Migrations
{
    [DbContext(typeof(APIDbContext))]
    [Migration("20240430221700_entity_name_correction")]
    partial class entity_name_correction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tcc.EntityModels.ProdutoEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_creation");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_modified");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("detalhe");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("produto_guid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.Property<int?>("VendaEntityModelId")
                        .HasColumnType("integer");

                    b.Property<string>("dt_lote")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dt_lote");

                    b.HasKey("Id");

                    b.HasIndex("VendaEntityModelId");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("tcc.EntityModels.VendaEntityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("venda_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_creation");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dt_modified");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real")
                        .HasColumnName("valor_total");

                    b.HasKey("Id")
                        .HasName("pk_venda_id");

                    b.ToTable("vendas", (string)null);
                });

            modelBuilder.Entity("tcc.EntityModels.ProdutoEntityModel", b =>
                {
                    b.HasOne("tcc.EntityModels.VendaEntityModel", null)
                        .WithMany("Produto")
                        .HasForeignKey("VendaEntityModelId");
                });

            modelBuilder.Entity("tcc.EntityModels.VendaEntityModel", b =>
                {
                    b.OwnsOne("tcc.Models.DadosPagamentoModel", "DadosPagamento", b1 =>
                        {
                            b1.Property<int>("VendaEntityModelId")
                                .HasColumnType("integer");

                            b1.Property<int>("DadosPagamentoId")
                                .HasColumnType("integer")
                                .HasColumnName("pagamento_id");

                            b1.HasKey("VendaEntityModelId");

                            b1.ToTable("vendas");

                            b1.WithOwner()
                                .HasForeignKey("VendaEntityModelId");

                            b1.OwnsOne("tcc.Models.Cartao", "Cartao", b2 =>
                                {
                                    b2.Property<int>("DadosPagamentoModelVendaEntityModelId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Bandeira")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("cartao_bandeira");

                                    b2.Property<string>("CodigoSeguranca")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("cartao_codigo_seguranca");

                                    b2.Property<string>("DtValidade")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("cartao_dt_validade");

                                    b2.Property<int>("Id")
                                        .HasColumnType("integer")
                                        .HasColumnName("cartao_id");

                                    b2.Property<string>("NomeCartao")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("cartao_nome");

                                    b2.Property<string>("NumeroCartao")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("cartao_numero");

                                    b2.Property<string>("Tipo")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("cartao_tipo");

                                    b2.HasKey("DadosPagamentoModelVendaEntityModelId");

                                    b2.ToTable("vendas");

                                    b2.WithOwner()
                                        .HasForeignKey("DadosPagamentoModelVendaEntityModelId");
                                });

                            b1.Navigation("Cartao")
                                .IsRequired();
                        });

                    b.OwnsOne("tcc.Models.DadosPessoaisModel", "DadosPessoais", b1 =>
                        {
                            b1.Property<int>("VendaEntityModelId")
                                .HasColumnType("integer");

                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("pessoal_cpf");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("pessoal_nome");

                            b1.Property<string>("Sobrenome")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("pessoal_sobrenome");

                            b1.HasKey("VendaEntityModelId");

                            b1.ToTable("vendas");

                            b1.WithOwner()
                                .HasForeignKey("VendaEntityModelId");
                        });

                    b.OwnsOne("tcc.Models.EnderecoModel", "Endereco", b1 =>
                        {
                            b1.Property<int>("VendaEntityModelId")
                                .HasColumnType("integer");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("endereco_bairro");

                            b1.Property<int>("Cep")
                                .HasColumnType("integer")
                                .HasColumnName("endereco_cep");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("endereco_cidade");

                            b1.Property<int>("EnderecoId")
                                .HasColumnType("integer")
                                .HasColumnName("endereco_id");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("endereco_estado");

                            b1.Property<int>("Numero")
                                .HasColumnType("integer")
                                .HasColumnName("endereco_numero");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("endereco_rua");

                            b1.HasKey("VendaEntityModelId");

                            b1.ToTable("vendas");

                            b1.WithOwner()
                                .HasForeignKey("VendaEntityModelId");
                        });

                    b.Navigation("DadosPagamento")
                        .IsRequired();

                    b.Navigation("DadosPessoais")
                        .IsRequired();

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("tcc.EntityModels.VendaEntityModel", b =>
                {
                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
